# Generated by Django 5.0.1 on 2024-01-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
