# Generated by Django 5.0.1 on 2024-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='network.post'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
