# Generated by Django 5.0.1 on 2024-02-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_picture_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
