# Generated by Django 5.0.1 on 2024-02-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
    ]
