# Generated by Django 5.0.1 on 2024-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_remove_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
