# Generated by Django 5.0.1 on 2024-02-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
    ]
